# Generated by Django 6.0.1 on 2026-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_sailoruser_email_sailoruser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoruser',
            name='is_activate',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
