# Generated by Django 6.0.1 on 2026-02-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sailoruser_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='is_activate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
