# Generated by Django 6.0.1 on 2026-02-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sailoruser_is_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailoruser',
            name='is_activate',
        ),
    ]
