# Generated by Django 6.0.1 on 2026-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_sailoruser_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='mobile_number',
            field=models.PositiveBigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
