# Generated by Django 6.0.1 on 2026-02-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sailoruser_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sailoruser',
            old_name='user',
            new_name='email',
        ),
    ]
