# Generated by Django 6.0.1 on 2026-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_sailoruser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoruser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sailoruser',
            name='otp',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sailoruser',
            name='otp_created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
