# Generated by Django 6.0.1 on 2026-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sailoruser_is_verified_sailoruser_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
