# Generated by Django 6.0.1 on 2026-02-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_sailoruser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoruser',
            name='is_google_auth',
            field=models.BooleanField(default=False),
        ),
    ]
