# Generated by Django 6.0.1 on 2026-02-11 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sailoruser_is_google_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='otp_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
