# Generated by Django 6.0.1 on 2026-02-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_soar_category_soar_quiz_average_score_soar_quiz_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soar_quiz_answer',
            name='SailorUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='api.sailoruser'),
            preserve_default=False,
        ),
    ]
