# Generated by Django 6.0.1 on 2026-02-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_soar_quiz_answer_sailoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='soar_quiz_average_score',
            name='SailorUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='average_scores', to='api.sailoruser'),
            preserve_default=False,
        ),
    ]
